<?php defined('C5_EXECUTE') or die(_("Access Denied."));
$time_start = microtime(true);
$altrvb = $h->hex_to_rvb($o->alternate_color);
?>
/* 
** Let's start with some override from dashboard option's page
** This file is generated by php and placed into theme_super_mint / elements / overrides.css.php
** Page name : <?php echo $c->getCollectionName() ?> / Theme preset Name : <?php echo $o->get_preset_title($o->pID) ?> / Theme preset ID : <?php echo $o->pID ?>

*/

/* --- Text Overrides --- */

<?php 
$p 	= new GoggleFontObject('p');
$alternate 	= new GoggleFontObject('alternate');
$h1 = new GoggleFontObject('h1');
$h2 = new GoggleFontObject('h2');
$h3 = new GoggleFontObject('h3');
$h4 = new GoggleFontObject('h4');
$small = new GoggleFontObject('small');
?>
html, .ccm-easyAccordion-title {
	color: <?=$o->p_color?>;
	font-size:<?=$p->normalsize?>px;
	<?=$p->getFamilyCss()?>
	font-weight: normal;
}
/* Body inherit from familly fonts */
.nav-pane li a {
	<?=$p->getFamilyCss()?>	
}
.rcrumbs a i {color: <?=$o->p_color?>}
<?php if ($o->nav_slide_arrow_color ) : ?>
a.close i {color:<?php echo $o->nav_slide_arrow_color ?>}
<?php endif ?>

a:not(.btn):not(.button) {color: <?=$o->a_color?>; } /* font-size:<?=$p->normalsize?>px; */
a:not(.btn):not(.button):hover  {color: <?=$o->a_hover_color?>}
a:not(.btn):not(.button):visited   {color: <?=$o->a_visited_color?>}

/* Resets for Concrete5 ui */
	/* #supermint ul#ccm-main-nav a, #supermint ul#ccm-system-nav a {color: #666} */
	#supermint .ccm-ui a:not(.btn):not(.ccm-menu-icon), #supermint .ccm-dialog-tabs>li>a {color: #0088cc}
	#supermint div.ccm-menu ul a, #supermint div.ccm-editor-controls ul li a, #supermint div.ccm-editor-controls ul li {color:#333}



.alternate, .tp-caption.big_alternate  {
	color: <?=$o->alternate_color?>;
	<?=$alternate->getFamilyCss()?>
}
.altbg {
	background-color:<?=$o->alternate_color?>;
}
.kenBurns h1 {
	background-color:<?php echo $o->alternate_color ?>;
	background-color:rgba(<?php echo $altrvb[0] . ',' . $altrvb[1] . ',' . $altrvb[2] ?>,.6);
}
/* Things that inherit from 'alternate' color */

.boxed-c a:hover, .boxed-c a:focus, .boxed-c a.active, .prop-list .price
{
	color: <?=$o->alternate_color?>;
}
.button-flat-primary, .button-primary, .ccm-input-button 
{
	background-color: <?=$o->alternate_color?>;	
}
.button-flat-primary:hover,  button-primary:hover {
	background-color:<?php echo $h->adjustBrightness($o->alternate_color,20) ?>
}
.hint--alternate:after { background-color: <?=$o->alternate_color?>; text-shadow: 0 -1px 0px <?php echo $h->adjustBrightness($o->alternate_color,-20) ?>; }
.hint--alternate.hint--top:before { border-top-color: <?=$o->alternate_color?>; }
.hint--alternate.hint--bottom:before { border-bottom-color: <?=$o->alternate_color?>; }
.hint--alternate.hint--left:before { border-left-color: <?=$o->alternate_color?>; }
.hint--alternate.hint--right:before { border-right-color: <?=$o->alternate_color?>; }

/* - Headers - */

h1 {
	color: <?=$o->h1_color?>;
	font-size:<?=$h1->normalsize?>px;
	<?=$h1->getFamilyCss()?>
}
h2 {
	color: <?=$o->h2_color?>;
	font-size:<?=$h2->normalsize?>px;
	<?=$h2->getFamilyCss()?>
}
h3 {
	color: <?=$o->h3_color?>;
	font-size:<?=$h3->normalsize?>px;
	<?=$h3->getFamilyCss()?>
}
h4 {
	color: <?=$o->h4_color?>;
	font-size:<?=$h4->normalsize?>px;
	<?=$h4->getFamilyCss()?>
}
h1 a,h2 a,h3 a,h4 a,h5 a {color:<?=$o->h_link_color?> !important}
h1 a:hover,h2 a:hover,h3 a:hover,h4 a:hover,h5 a:hover {color:<?=$o->h_hover_color?>}
h1 small,h2 small,h3 small,h4 small,h5 small {<?=$small->getFamilyCss()?>; font-size:<?=$o->small_tag_size?>em}

/* -- Footer Typo -- */

#footer *:not(.button):not(.ccm-input-button):not(input):not(textarea)  {
	color:<?=$o->footer_t_color?>
}
#footer h1, #footer h2, #footer h3, #footer h4, #footer a, #footer strong {
	color:<?=$o->footer_h_color?>	
}
#footer a:not(.button):not(.ccm-input-button):not(textarea) {
	color:<?=$o->footer_a_color?>
}
/* -- Slider Typo -- */

.tp-caption.big_white,
.tp-caption.big_colored ,
.tp-caption.big_3d_white,
.tp-caption.very_big_white, 
.tp-caption.big_black ,
.tp-caption.black {
	<?=$h1->getFamilyCss()?>
}
.tp-caption.medium_white_text,
.tp-caption.large_white_text {
	<?=$h2->getFamilyCss()?>

}
.tp-caption.small_box_white,
.tp-caption.medium_box_white,
.tp-caption.big_box_white,
.tp-caption.paragraph ,
.tp-caption.white_boxshadow {
	color: <?=$o->p_color?>;
	<?=$p->getFamilyCss()?>
}

/* --- Background colors & pattern overrides --- */

#fixed-top {background: <?php echo $o->bg_top ?> url(<?php echo $h->get_ressource_relative_path($o->bg_top_pattern,'patterns' ) ?>); <?php $o->_fixed_top ? '' : 'position:relative' ?>}
#middle {background: <?php echo $o->bg_body_color ?> url(<?php echo $h->get_ressource_relative_path($bodypattern,'patterns' ) ?>)}
#bottom {background: <?php echo $o->bg_bottom_color ?> url(<?php echo $h->get_ressource_relative_path($o->bg_bottom_pattern,'patterns' ) ?>)}
#footerpush, body {background: <?php echo $o->bg_footer_color ?> url(<?php echo $h->get_ressource_relative_path($o->bg_footer_pattern,'patterns' ) ?>)}
#pageslide {background: <?php echo $o->bg_pageslide ?> url(<?php echo $h->get_ressource_relative_path($o->bg_pageslide_pattern,'patterns' ) ?>)}
#pageslide * {color: <?php echo $o->text_pageslide ?>}
#top-page {background-color:<?php echo $o->bg_toppage_color ?>;}
.content {background-color:<?php echo $o->bg_main_color ?>;}
<?php if ($o->_disable_border_main('colors')) : ?>
.content, #top-page { border:1px solid transparent}
<?php endif ?>
.sidebar {background-color:<?php echo $o->bg_sidebar_color ?>;}

<?php if (!$o->__footer_fixed) : ?>
#footer { position:relative}
<?php endif ?>

/* -- Unbordered -- */

#header_unbordered, #under_header_unbordered, #middle_unbordered {background: <?php echo $o->bg_header_u_color ?> url(<?php echo $h->get_ressource_relative_path($o->bg_header_u_pattern,'patterns' ) ?>)}
#main_unbordered {background: <?php echo $o->bg_main_u_color ?> url(<?php echo $h->get_ressource_relative_path($o->bg_main_u_custom_pattern ? $o->bg_main_u_custom_pattern : $o->bg_main_u_pattern,'patterns' ) ?>)}
#under_main_unbordered {background: <?php echo $o->bg_undermain_u_color ?> url(<?php echo $h->get_ressource_relative_path($o->bg_undermain_u_pattern,'patterns' ) ?>)}

/* -- Navigation -- */

/* - Top-nav is buttons  */
#top,
.meganizr > li > ul, 
.mzr-drop > ul, 
.stack-pane,  
.meganizr .product-nav-pane  { 
	background: <?php echo $o->bg_nav_slide ?> url(<?php echo $h->get_ressource_relative_path($o->bg_nav_slide_pattern,'patterns' ) ?>)
}
#top_nav, #fixed-nav{  
	border-top-color: <?php echo $h->adjustBrightness($o->bg_nav,-10)?>;
	border-bottom: <?php echo $h->adjustBrightness($o->bg_nav,-20)?>;
	background: <?php echo $o->bg_nav ?>;
	background-image: linear-gradient( to bottom, <?php echo $o->bg_nav ?>, <?php echo $h->adjustBrightness($o->bg_nav,-10) ?>);
	background: -webkit-linear-gradient( <?php echo $o->bg_nav ?>, <?php echo $h->adjustBrightness($o->bg_nav,-10) ?>);

}

#top_nav ul.nav > li > a, #top_nav .meganizr a:not(.button), #top_nav ul.nav > li > span, #top_nav ul.nav > li > span > a > i {color: <?php echo $o->top_nav_a ?>; <?php if ($o->_disable_box_shadow_active_nav('colors')) : ?>text-shadow:none <?php else : ?>  text-shadow: 0 -1px <?php echo $h->adjustBrightness($o->bg_nav,-20) ?> <?php endif ?>;}

/* Le selectionné du premier niveau */

#top_nav ul.nav > li.active > a,
#top_nav ul.nav > li.nav-selected > a, 
#top_nav ul.nav > li.nav-path-selected > a
 { 
	border-bottom-color: <?php echo $o->bg_nav_selected ?>;
	background:<?php echo $o->top_nav_hover ?>;
	background-image: linear-gradient(to bottom, <?php echo $h->adjustBrightness($o->top_nav_hover,2) ?>, <?php echo $h->adjustBrightness($o->top_nav_hover,-10) ?>);
	background-image: -webkit-linear-gradient(<?php echo $h->adjustBrightness($o->top_nav_hover,10) ?>, <?php echo $h->adjustBrightness($o->top_nav_hover,-10) ?>);
	color:<?php echo $o->top_nav_hover_link?>;
	<?php if ($o->_disable_box_shadow_active_nav('colors')) : ?>
	box-shadow: none;
	-webkit-box-shadow:none;
	<?php endif ?>
}
/* le Hover du premier niveau */

#top_nav .meganizr > li:hover > a,
#top_nav ul.nav > li.active > a:hover,
#top_nav ul.nav > li > a:active
	{
	 background-color:<?php echo $o->top_nav_hover ?> !important;
	 color:<?php echo $o->top_nav_hover_link?>;
	 background-image:none;
	} 
.secondary-nav li a {color: <?php echo $o->secondary_nav_color ?>}

/* -- Text into subnavs -- */

<?php $rvb = $h->hex_to_rvb($o->top_nav_p) ?>
.nav-panes p, .nav-panes * {color: <?php echo $o->nav_slide_p_color ?>}
#top .nav-pane li a, #top .nav-pane a,  #top_nav ul.meganizr li.mzr-drop li a:not(.button) {color: <?php echo $o->nav_slide_a_color ?>; } 
.nav-pane h1,.nav-pane h2,.nav-pane h3,.nav-pane h4,.nav-pane h5, li .head-title {color: <?php echo $o->nav_slide_h_color ?>; border-color: <?php echo $o->nav_slide_h_color ?>} 

/* -- E-commerce -- */
.preview.og-expander {background: <?php echo $o->bg_preview_color ?> url(<?php echo $h->get_ressource_relative_path($o->bg_preview_pattern,'patterns' ) ?>)}
.cart-quantity-wrapper *, .cart-quantity-wrapper a, .cart-quantity-wrapper i {color:<?php echo $o->txt_cart_color ?>!important}
.cart-quantity-wrapper { background-color: <?php echo $o->bg_cart_color ?>; color:<?php echo $o->txt_cart_color ?>}


/* --- Large desktop */
@media (min-width: 1200px) {

	body, .ccm-easyAccordion-title {font-size:<?=$p->widesize?>px}
	/* a {font-size:<?=$p->widesize?>px} */
	h1 {font-size:<?=$h1->widesize?>px}
	h2 {font-size:<?=$h2->widesize?>px}
	h3 {font-size:<?=$h3->widesize?>px}
	h4 {font-size:<?=$h4->widesize?>px}

}
 
/* --- Portrait tablet to landscape and desktop */
@media (min-width: 768px) and (max-width: 979px) {

	body {font-size:<?=$p->tabletsize?>px}
	/* a {font-size:<?=$p->tabletsize?>px} */
	h1 {font-size:<?=$h1->tabletsize?>px}
	h2 {font-size:<?=$h2->tabletsize?>px}
	h3 {font-size:<?=$h3->tabletsize?>px}
	h4 {font-size:<?=$h4->tabletsize?>px}

}
 
/* --- Landscape phone to portrait tablet */
@media (max-width: 767px) {
	#top_nav li {background-color: <?php echo $o->bg_nav ?>}
	p,li {font-size:<?=$p->fullsize?>px}
	h1 {font-size:<?=$h1->fullsize?>px}
	h2 {font-size:<?=$h2->fullsize?>px}
	h3 {font-size:<?=$h3->fullsize?>px}
	h4 {font-size:<?=$h4->fullsize?>px}	

	<?php if($o->__select_nav_mobile) : ?>
	#mobile_nav {
		display:block;
	}
	#nav_tabs, .meganizr.nav {
		display:none;
	}
	<?php endif ?>
}

/* --- Landscape phones and down */
@media (max-width: 480px) { 

}

/*<?php 
$time_end = microtime(true);
$time = $time_end - $time_start;

echo "CSS $time secondes\n";
 ?>*/