<?php   defined('C5_EXECUTE') or die(_("Access Denied."));
$responsive = !$t->__disable_mobile_detection;
?>

/* 
** Let's start with some override from dashboard option's page
** This file is generated by php and placed into theme_silence / elements / overrides.css.php
** Page name : <?php  echo $c->getCollectionName() ?> / Theme preset Name : <?php  echo $t->get_preset_title($t->pID) ?> / Theme preset ID : <?php  echo $t->pID ?>

*/

<?php  if (!$t->__display_page_title && !$t->__display_page_desc && !$t->__display_breadcrumb) : ?>
#middle .content {padding-top:0}
<?php  endif ?>

<?php  $t->set_toggle_option_name('colors')?>

h1 a,h2 a,h3 a,h4 a,h5 a {color:<?php echo $t->h_link_color?>}
h1 a:hover,h2 a:hover,h3 a:hover,h4 a:hover,h5 a:hover {color:<?php echo $t->h_hover_color?>}
h1 a:visited,h2 a:visited,h3 a:visited,h4 a:visited,h5 a:visited {color:<?php echo $t->h_visited_color?>}
    
h1 {color:<?php echo $t->h1_color?>}
h2 {color:<?php echo $t->h2_color?>}
h3 {color:<?php echo $t->h3_color?>}
h4 {color:<?php echo $t->h4_color?>}
h5 {color:<?php echo $t->h5_color?>}
p, body#silence {color:<?php echo $t->p_color?>}
a {color:<?php echo $t->a_color?>}
.ccm-next-previous-wrapper a { color:<?php echo $t->a_color?>}
a:visited { color:<?php echo $t->a_visited_color?>}
a:hover { color:<?php echo $t->a_hover_color?>}
.ccm-next-previous-wrapper a:hover {color:<?php echo $t->a_hover_color?>}



/*-----  Buttons ------*/
      
a.butn,button,a.butn:visited,a.butn span,button span { background-image : url(<?php echo $h->get_ressource_relative_path($t->bg_button,'buttons')?>)}
a.butn,button,a.butn:visited {color:<?php echo $t->button_text_color?>}
a.butn:hover span { color:<?php echo $t->button_text_hover_color?>}
a.butn:hover { background-image : url(<?php echo $h->get_ressource_relative_path($t->bg_button_hover,'buttons')?>)}
a.butn:hover span { background-image: url(<?php echo $h->get_ressource_relative_path($t->bg_button_hover,'buttons')?>)}

/*-----  Sidebar Title ------*/

/* ---- Left ---- */
#sidebar h3 {background-image:url(<?php echo $h->get_ressource_relative_path($t->bg_left_sidebar_title,'left_sidebar_title')?>)}
#sidebar h3 {color:<?php echo $t->left_sidebar_title_color?>}
#sidebar h3 a {color:<?php echo $t->left_sidebar_title_link_color?>}
    
#sidebar.right-sidebar h3 {background-image : url(<?php echo $h->get_ressource_relative_path($t->bg_right_sidebar_title,'right_sidebar_title')?>)}
#sidebar.right-sidebar h3 {color:<?php echo $t->right_sidebar_title_color?>}
#sidebar.right-sidebar h3 a {color:<?php echo $t->right_sidebar_title_link_color?>}

/*-----  Top Nav ------*/

<?php  $t->set_toggle_option_name('colors');
$col = $h->hex_to_rvb($t->nav_background_selected_color);
 ?>
#top .silence-main-nav a.first-level {color:<?php echo $t->nav_first_level_color?>}
#top #main-nav ul li li a {color:<?php echo $t->nav_second_level_color?>}
#top  #main-nav ul li ul li ul li a {color:<?php echo $t->nav_third_level_color?>}
#main-nav ul li.nav-path-selected a,#main-nav ul li.nav-path-selected span,#main-nav ul li.nav-selected a,#main-nav ul li.nav-selected span,#main-nav ul a:hover,#main-nav ul a.sfHover,#main-nav ul li.first-level.sfHover a.first-level {
    color:<?php echo $t->nav_third_level_color?> }

#main-nav ul li li a:hover {background:rgba(<?php echo "$col[0],$col[1],$col[2]" ?>,.4) }

<?php  if (!$t->__top_nav_shadow_enabled) :?>
#main-nav a  { text-shadow :none }
#main-nav ul li li a:hover,#main-nav ul li li a:hover span {text-shadow: none}
<?php  endif ?>  


/*-----  Pattern & backgrounds ------*/
<?php 
$t->set_toggle_option_name('background');
$toppattern = $t->bg_top_custom ? $t->bg_top_custom : $t->bg_top_pattern;
$bodypattern = $t->bg_body_custom ? $t->bg_body_custom : $t->bg_body_pattern;
$footerpattern = $t->bg_footer_custom ? $t->bg_footer_custom : $t->bg_footer_pattern;
?>

/* ---- Body & top ---- */

body#silence { background-image:url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_body_color, 1 , 6 ), 'pattern' => $bodypattern))?>)}
#top { background-image: url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_top_color, 1 , 6 ), 'pattern' => $toppattern, 'color-height' => $t->bg_top_height, 'shadow' => $t->bg_top_shadow))?>)}

/* ---- Main nav ---- */

#main-nav ul li ul { background:url(<?php echo $h->get_nav_background_rel_path(array('level'=>1,'light'=>$t->bg_nav_light, 'color' => substr($t->bg_nav_color, 1 , 6 )))?>)}
#main-nav ul li li ul { background :url(<?php echo $h->get_nav_background_rel_path(array('level'=>2,'light'=>$t->bg_nav_light, 'color' => substr($t->bg_second_nav_color, 1 , 6 )))?>)}

/* ---- Mobile nav ---- */
<?php $col = $h->hex_to_rvb($t->nav_second_level_color) ?>
#mobile-top {background-color:<?php echo $t->bg_top_color ?>} /* -- fixed nav on top -- */
.mm-menu {color: rgba(<?php echo "$col[0],$col[1],$col[1]" ?>,.8)} /* -- the main color on text -- */
.mm-ismenu {background-color:<?php echo $t->bg_nav_color ?>} /* -- the main bg -- */
.mm-menu .mm-list > li:after,
.mm-menu .mm-list > li > a.mm-subopen:before
	 {border-color: rgba(<?php echo "$col[0],$col[1],$col[1]" ?>,.1)} /* -- the thin line -- */

/* ---- Footer ---- */

#footer .container { background:url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_footer_page_color, 1 , 6 ), 'pattern' => $footerpattern, 'color-height' => 800 , 'shadow' => $t->bg_footer_shadow))?>)}
#footer .row { background-color:<?php echo $t->bg_footer_color?>}

<?php  if (!$t->__bg_top_light) :?>
#top .container {background-image :none}
<?php  endif ?>
/* ---- Main content & sidebar ---- */

#middle .row .content {background-color:<?php echo $t->bg_main_color?>}
#sidebar {background-color:<?php echo $t->bg_sidebar_color?>}


@media (min-width: 1200px) {
	#top { background-image: url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_top_color, 1 , 6 ), 'pattern' => $toppattern, 'color-height' => $t->bg_top_height_large, 'shadow' => $t->bg_top_shadow))?>)}
}
@media (min-width: 768px) and (max-width: 979px) {
	#top { background-image: url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_top_color, 1 , 6 ), 'pattern' => $toppattern, 'color-height' => $t->bg_top_height_medium, 'shadow' => $t->bg_top_shadow))?>)}
}
@media (max-width: 767px) {
	#top { background-image: url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_top_color, 1 , 6 ), 'pattern' => $toppattern, 'color-height' => $t->bg_top_height_small, 'shadow' => $t->bg_top_shadow))?>)}
}
@media (max-width: 480px) {
	#top { background-image: url(<?php echo $h->get_pattern_relative_path(array('color' => substr($t->bg_top_color, 1 , 6 ), 'pattern' => $toppattern, 'color-height' => $t->bg_top_height_mobile_xsmall, 'shadow' => $t->bg_top_shadow))?>)}
}

@media (max-width: 979px) {
<?php if ($responsive) : ?>
  #middle {
		margin-top: 0px;
	} 
	#top .container {
	min-height:0;
	}
  #main-nav {
  	display: none;
  }
  #mobile-top {
  	display: block;
  	width: 100%;
  	height: 40px;
  	padding: 0 50px;
  	line-height: 40px;
  	background-color: #464F5C;
  	z-index: 998;
  }
  
  .ccm-layout-cell {
    width: 100% !important;
  }
  .ccm-layout-col-spacing {
    margin: 0 !important;
  }
 <?php else : ?>
 	
 <?php endif ?>
}